spring.application.name=account-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/conta_db?CreateDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create-drop

spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
logging.level.org.apache.kafka=DEBUG


spring.mongodb.uri=mongodb://localhost:27017/transfer_db
